[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
]

[etherscan]
base = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
base = "${BASE_RPC_URL}"

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
